# Generated by Django 5.2.8 on 2025-11-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='모임 이름')),
                ('description', models.TextField(blank=True, verbose_name='모임 설명')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='band/covers/', verbose_name='커버 이미지')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='band/profiles/', verbose_name='프로필 이미지')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('join_approval_required', models.BooleanField(default=False, verbose_name='가입 승인 필요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bands', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '밴드',
                'verbose_name_plural': '밴드',
            },
        ),
        migrations.CreateModel(
            name='BandComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='band.bandcomment', verbose_name='부모 댓글')),
            ],
            options={
                'verbose_name': '밴드 댓글',
                'verbose_name_plural': '밴드 댓글',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BandCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='band.bandcomment', verbose_name='댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '밴드 댓글 좋아요',
                'verbose_name_plural': '밴드 댓글 좋아요',
            },
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '방장'), ('admin', '관리자'), ('member', '멤버')], default='member', max_length=20, verbose_name='역할')),
                ('status', models.CharField(choices=[('active', '활성'), ('pending', '대기중'), ('banned', '차단됨')], default='active', max_length=20, verbose_name='상태')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('last_visited_at', models.DateTimeField(auto_now=True, verbose_name='마지막 방문일')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='band.band', verbose_name='밴드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '밴드 멤버',
                'verbose_name_plural': '밴드 멤버',
            },
        ),
        migrations.CreateModel(
            name='BandPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('post_type', models.CharField(choices=[('general', '일반'), ('announcement', '공지'), ('schedule', '일정'), ('vote', '투표')], default='general', max_length=20, verbose_name='글 유형')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='고정')),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('comment_count', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='band.band', verbose_name='밴드')),
            ],
            options={
                'verbose_name': '밴드 게시글',
                'verbose_name_plural': '밴드 게시글',
                'ordering': ['-is_pinned', '-is_notice', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bandcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='band.bandpost', verbose_name='게시글'),
        ),
        migrations.CreateModel(
            name='BandPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='band/posts/', verbose_name='이미지')),
                ('order_index', models.IntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='band.bandpost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '밴드 게시글 이미지',
                'verbose_name_plural': '밴드 게시글 이미지',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='BandPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='band.bandpost', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '밴드 게시글 좋아요',
                'verbose_name_plural': '밴드 게시글 좋아요',
            },
        ),
        migrations.CreateModel(
            name='BandSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='모임 참가 조건')),
                ('start_datetime', models.DateTimeField(verbose_name='시작 일시')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='종료 일시')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='최대 참가 인원')),
                ('current_participants', models.IntegerField(default=0, verbose_name='현재 참가 인원')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='승인 필요')),
                ('application_deadline', models.DateTimeField(blank=True, null=True, verbose_name='신청 마감일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='band.band', verbose_name='밴드')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='band.bandpost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '밴드 일정',
                'verbose_name_plural': '밴드 일정',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BandScheduleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('rejected', '거부됨'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='상태')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='거부 사유')),
                ('notes', models.TextField(blank=True, verbose_name='신청 메모')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='band.bandschedule', verbose_name='일정')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_applications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '밴드 일정 신청',
                'verbose_name_plural': '밴드 일정 신청',
            },
        ),
        migrations.CreateModel(
            name='BandVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='투표 제목')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='복수 선택')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='종료 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='band.bandpost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '밴드 투표',
                'verbose_name_plural': '밴드 투표',
            },
        ),
        migrations.CreateModel(
            name='BandVoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200, verbose_name='옵션 텍스트')),
                ('vote_count', models.IntegerField(default=0, verbose_name='투표 수')),
                ('order_index', models.IntegerField(default=0, verbose_name='순서')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='band.bandvote', verbose_name='투표')),
            ],
            options={
                'verbose_name': '밴드 투표 옵션',
                'verbose_name_plural': '밴드 투표 옵션',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='BandVoteChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_vote_choices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='band.bandvote', verbose_name='투표')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='band.bandvoteoption', verbose_name='옵션')),
            ],
            options={
                'verbose_name': '밴드 투표 선택',
                'verbose_name_plural': '밴드 투표 선택',
            },
        ),
        migrations.AddIndex(
            model_name='band',
            index=models.Index(fields=['created_by'], name='band_band_created_345cac_idx'),
        ),
        migrations.AddIndex(
            model_name='band',
            index=models.Index(fields=['is_public'], name='band_band_is_publ_5238f0_idx'),
        ),
        migrations.AddIndex(
            model_name='bandcommentlike',
            index=models.Index(fields=['comment'], name='band_bandco_comment_1dd4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='bandcommentlike',
            index=models.Index(fields=['user'], name='band_bandco_user_id_90e30e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandcommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='bandmember',
            index=models.Index(fields=['band'], name='band_bandme_band_id_6f3a09_idx'),
        ),
        migrations.AddIndex(
            model_name='bandmember',
            index=models.Index(fields=['user'], name='band_bandme_user_id_38f4db_idx'),
        ),
        migrations.AddIndex(
            model_name='bandmember',
            index=models.Index(fields=['role'], name='band_bandme_role_c2881f_idx'),
        ),
        migrations.AddIndex(
            model_name='bandmember',
            index=models.Index(fields=['status'], name='band_bandme_status_2b8d7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandmember',
            unique_together={('band', 'user')},
        ),
        migrations.AddIndex(
            model_name='bandpost',
            index=models.Index(fields=['band'], name='band_bandpo_band_id_d82544_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpost',
            index=models.Index(fields=['author'], name='band_bandpo_author__4f2153_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpost',
            index=models.Index(fields=['post_type'], name='band_bandpo_post_ty_2a124c_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpost',
            index=models.Index(fields=['is_pinned'], name='band_bandpo_is_pinn_ee14ff_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpost',
            index=models.Index(fields=['-created_at'], name='band_bandpo_created_7a1213_idx'),
        ),
        migrations.AddIndex(
            model_name='bandcomment',
            index=models.Index(fields=['post'], name='band_bandco_post_id_c4e0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bandcomment',
            index=models.Index(fields=['author'], name='band_bandco_author__5bbe03_idx'),
        ),
        migrations.AddIndex(
            model_name='bandcomment',
            index=models.Index(fields=['parent'], name='band_bandco_parent__f605f1_idx'),
        ),
        migrations.AddIndex(
            model_name='bandcomment',
            index=models.Index(fields=['-created_at'], name='band_bandco_created_07143a_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpostimage',
            index=models.Index(fields=['post'], name='band_bandpo_post_id_de2477_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpostimage',
            index=models.Index(fields=['post', 'order_index'], name='band_bandpo_post_id_a758b8_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpostlike',
            index=models.Index(fields=['post'], name='band_bandpo_post_id_28de87_idx'),
        ),
        migrations.AddIndex(
            model_name='bandpostlike',
            index=models.Index(fields=['user'], name='band_bandpo_user_id_2340a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandpostlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='bandschedule',
            index=models.Index(fields=['band'], name='band_bandsc_band_id_e8d32a_idx'),
        ),
        migrations.AddIndex(
            model_name='bandschedule',
            index=models.Index(fields=['post'], name='band_bandsc_post_id_ef3715_idx'),
        ),
        migrations.AddIndex(
            model_name='bandschedule',
            index=models.Index(fields=['start_datetime'], name='band_bandsc_start_d_a0274e_idx'),
        ),
        migrations.AddIndex(
            model_name='bandschedule',
            index=models.Index(fields=['created_by'], name='band_bandsc_created_d7569b_idx'),
        ),
        migrations.AddIndex(
            model_name='bandschedule',
            index=models.Index(fields=['application_deadline'], name='band_bandsc_applica_928ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='bandscheduleapplication',
            index=models.Index(fields=['schedule'], name='band_bandsc_schedul_66c378_idx'),
        ),
        migrations.AddIndex(
            model_name='bandscheduleapplication',
            index=models.Index(fields=['user'], name='band_bandsc_user_id_32fd78_idx'),
        ),
        migrations.AddIndex(
            model_name='bandscheduleapplication',
            index=models.Index(fields=['status'], name='band_bandsc_status_0630b8_idx'),
        ),
        migrations.AddIndex(
            model_name='bandscheduleapplication',
            index=models.Index(fields=['-applied_at'], name='band_bandsc_applied_e76bde_idx'),
        ),
        migrations.AddIndex(
            model_name='bandscheduleapplication',
            index=models.Index(fields=['reviewed_by'], name='band_bandsc_reviewe_e7af79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandscheduleapplication',
            unique_together={('schedule', 'user')},
        ),
        migrations.AddIndex(
            model_name='bandvote',
            index=models.Index(fields=['post'], name='band_bandvo_post_id_bc07d7_idx'),
        ),
        migrations.AddIndex(
            model_name='bandvote',
            index=models.Index(fields=['end_datetime'], name='band_bandvo_end_dat_30d1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bandvoteoption',
            index=models.Index(fields=['vote'], name='band_bandvo_vote_id_9937d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bandvoteoption',
            index=models.Index(fields=['vote', 'order_index'], name='band_bandvo_vote_id_0d90e6_idx'),
        ),
        migrations.AddIndex(
            model_name='bandvotechoice',
            index=models.Index(fields=['vote'], name='band_bandvo_vote_id_0531e3_idx'),
        ),
        migrations.AddIndex(
            model_name='bandvotechoice',
            index=models.Index(fields=['option'], name='band_bandvo_option__85e2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='bandvotechoice',
            index=models.Index(fields=['user'], name='band_bandvo_user_id_aa28d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandvotechoice',
            unique_together={('vote', 'user', 'option')},
        ),
    ]
