# Generated by Django 5.2.8 on 2025-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_type',
            field=models.CharField(choices=[('flash', '번개'), ('group', '모임'), ('club', '동호회')], default='group', max_length=20, verbose_name='모임 유형'),
        ),
    ]
