# Generated by Django 5.2.8 on 2025-11-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_band_band_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='region',
            field=models.CharField(choices=[('all', '전체'), ('seoul', '서울'), ('gyeonggi', '경기'), ('gangwon', '강원'), ('chungnam', '충남'), ('chungbuk', '충북'), ('jeonnam', '전남'), ('jeonbuk', '전북'), ('gyeongnam', '경남'), ('gyeongbuk', '경북'), ('busan', '부산'), ('daegu', '대구'), ('incheon', '인천'), ('gwangju', '광주'), ('daejeon', '대전'), ('ulsan', '울산'), ('sejong', '세종'), ('jeju', '제주')], default='all', max_length=20, verbose_name='지역'),
        ),
    ]
