# Generated by Django 5.2.8 on 2025-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_band_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='region',
            field=models.CharField(choices=[('all', '전체'), ('capital', '수도권'), ('busan', '부산권'), ('daegu', '대구권'), ('gwangju', '광주권'), ('daejeon', '대전권'), ('ulsan', '울산권'), ('jeju', '제주권')], default='all', max_length=20, verbose_name='지역'),
        ),
    ]
