# Generated by Django 5.2.8 on 2025-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_alter_band_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='flash_region_detail',
            field=models.CharField(blank=True, help_text='번개 생성 시 선택한 구체 지역 (서울, 경기, 인천 등)', max_length=20, verbose_name='번개 구체 지역'),
        ),
    ]
