# Generated by Django 5.2.8 on 2025-12-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_band_flash_region_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='categories',
            field=models.CharField(blank=True, help_text='쉼표로 구분된 분류 코드 (flash,group,club)', max_length=100, verbose_name='분류 코드'),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_type',
            field=models.CharField(choices=[('flash', '번개'), ('group', '모임'), ('club', '동호회')], default='group', max_length=20, verbose_name='주요 유형'),
        ),
    ]
