# Generated by Django 5.2.8 on 2025-12-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def auto_approve_existing_bands(apps, schema_editor):
    """기존 모임/동호회를 자동 승인 처리"""
    Band = apps.get_model('band', 'Band')
    # 기존 모임/동호회는 모두 승인 처리
    Band.objects.filter(band_type__in=['group', 'club']).update(
        is_approved=True,
        approved_at=timezone.now()
    )


def reverse_auto_approve(apps, schema_editor):
    """마이그레이션 롤백 시 아무 작업도 하지 않음"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_band_categories_alter_band_band_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인 일시'),
        ),
        migrations.AddField(
            model_name='band',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bands', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AddField(
            model_name='band',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='모임/동호회 생성 시 관리자 승인이 필요합니다.', verbose_name='관리자 승인'),
        ),
        migrations.AddField(
            model_name='band',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='승인 거부 시 사유를 입력합니다.', verbose_name='거부 사유'),
        ),
        migrations.AlterField(
            model_name='band',
            name='region',
            field=models.CharField(choices=[('all', '전체'), ('capital', '수도권'), ('busan', '영남권'), ('daegu', '대구권'), ('gwangju', '호남권'), ('daejeon', '충청권'), ('ulsan', '울산권'), ('jeju', '제주권')], default='all', max_length=20, verbose_name='지역'),
        ),
        migrations.RunPython(auto_approve_existing_bands, reverse_auto_approve),
    ]
