# Generated by Django 5.2.8 on 2025-12-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0007_band_approved_at_band_approved_by_band_is_approved_and_more'),
    ]

    operations = [
    ]
