# Generated by Django 5.2.8 on 2025-12-03 19:12

from django.db import migrations, models


def migrate_description_data(apps, schema_editor):
    """기존 description 데이터를 처리"""
    Band = apps.get_model('band', 'Band')
    for band in Band.objects.all():
        # 기존 description이 500자 이상이면 detailed_description으로 이동
        if band.description and len(band.description) > 500:
            band.detailed_description = band.description
            # 처음 500자만 description에 유지
            band.description = band.description[:500]
            band.save(update_fields=['description', 'detailed_description'])


def reverse_migrate_description_data(apps, schema_editor):
    """마이그레이션 되돌리기"""
    Band = apps.get_model('band', 'Band')
    for band in Band.objects.all():
        # detailed_description이 있으면 description에 병합
        if band.detailed_description:
            if band.description:
                band.description = band.description + "\n\n" + band.detailed_description
            else:
                band.description = band.detailed_description
            band.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0008_fix_is_approved_default'),
    ]

    operations = [
        # 먼저 detailed_description 필드 추가 (TextField)
        migrations.AddField(
            model_name='band',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='모임에 대한 상세한 설명을 입력하세요.', verbose_name='모임 설명'),
        ),
        # 데이터 마이그레이션 실행
        migrations.RunPython(migrate_description_data, reverse_migrate_description_data),
        # description 필드를 CharField로 변경
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.CharField(blank=True, help_text='짧은 한줄 소개를 입력하세요.', max_length=500, verbose_name='모임 한줄 소개'),
        ),
    ]
