# Generated by Django 5.2.8 on 2025-12-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0009_band_detailed_description_alter_band_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmember',
            name='role',
            field=models.CharField(choices=[('owner', '모임장'), ('admin', '관리자'), ('member', '멤버')], default='member', max_length=20, verbose_name='역할'),
        ),
        migrations.AlterField(
            model_name='bandpost',
            name='post_type',
            field=models.CharField(choices=[('general', '일반'), ('announcement', '공지'), ('schedule', '일정'), ('vote', '투표'), ('question', '질문')], default='general', max_length=20, verbose_name='글 유형'),
        ),
    ]
