# Generated by Django 5.2.8 on 2025-12-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0010_alter_bandmember_role_alter_bandpost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpostimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='band.bandpost', verbose_name='게시글'),
        ),
    ]
