# Generated by Django 5.2.8 on 2025-12-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_alter_bandpostimage_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandScheduleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='번개 이미지 (3:4 비율 권장)', upload_to='band/schedules/images/', verbose_name='이미지')),
                ('order', models.IntegerField(default=0, help_text='이미지 표시 순서', verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='band.bandschedule', verbose_name='일정')),
            ],
            options={
                'verbose_name': '밴드 일정 이미지',
                'verbose_name_plural': '밴드 일정 이미지',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['schedule', 'order'], name='band_bandsc_schedul_3b0667_idx')],
            },
        ),
    ]
