# Generated by Django 5.2.8 on 2025-12-06 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0012_bandscheduleimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='deletion_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 승인 일시'),
        ),
        migrations.AddField(
            model_name='band',
            name='deletion_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_approved_bands', to=settings.AUTH_USER_MODEL, verbose_name='삭제 승인자'),
        ),
        migrations.AddField(
            model_name='band',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='모임 삭제 신청 시 사유를 입력합니다.', verbose_name='삭제 사유'),
        ),
        migrations.AddField(
            model_name='band',
            name='deletion_requested',
            field=models.BooleanField(default=False, help_text='모임 삭제 신청 여부', verbose_name='삭제 신청'),
        ),
        migrations.AddField(
            model_name='band',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 신청 일시'),
        ),
    ]
