# Generated by Django 5.2.8 on 2025-12-29 18:17

import band.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0013_band_deletion_approved_at_band_deletion_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandscheduleimage',
            name='image',
            field=models.ImageField(help_text='번개 이미지 (3:4 비율 권장)', upload_to=band.models.schedule_image_upload_to, verbose_name='이미지'),
        ),
    ]
