# Generated by Django 5.2.8 on 2026-01-10 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0014_alter_bandscheduleimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='북마크 일시')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='band.band', verbose_name='밴드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '밴드 북마크',
                'verbose_name_plural': '밴드 북마크',
                'indexes': [models.Index(fields=['band'], name='band_bandbo_band_id_dac8a6_idx'), models.Index(fields=['user'], name='band_bandbo_user_id_36e1f2_idx'), models.Index(fields=['-created_at'], name='band_bandbo_created_5b8014_idx')],
                'unique_together': {('band', 'user')},
            },
        ),
    ]
