# Generated by Django 5.2.8 on 2026-01-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0015_bandbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandschedule',
            name='bank_account',
            field=models.CharField(blank=True, help_text='참가비 입금 계좌 (예: 카카오뱅크 3333-00-0000000 홍길동)', max_length=100, verbose_name='입금 계좌'),
        ),
    ]
