# Generated by Django 5.2.8 on 2026-01-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0016_add_bank_account_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandschedule',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='수동으로 모집을 마감합니다', verbose_name='모집 마감'),
        ),
    ]
