# Generated by Django 5.2.8 on 2026-02-05 13:07

import badmintok.fields
import band.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0017_add_is_closed_to_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='cover_image',
            field=badmintok.fields.WebPImageField(blank=True, null=True, upload_to='band/covers/', verbose_name='커버 이미지'),
        ),
        migrations.AlterField(
            model_name='band',
            name='profile_image',
            field=badmintok.fields.WebPImageField(blank=True, null=True, upload_to='band/profiles/', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='bandpostimage',
            name='image',
            field=badmintok.fields.WebPImageField(upload_to='band/posts/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='bandscheduleimage',
            name='image',
            field=badmintok.fields.WebPImageField(help_text='번개 이미지 (3:4 비율 권장)', upload_to=band.models.schedule_image_upload_to, verbose_name='이미지'),
        ),
    ]
