# Generated by Django 5.2.8 on 2026-04-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0018_alter_band_cover_image_alter_band_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bandpost',
            name='answer',
            field=models.TextField(blank=True, help_text='질문(FAQ) 게시글의 답변', verbose_name='FAQ 답변'),
        ),
        migrations.AddField(
            model_name='bandpost',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='답변일'),
        ),
        migrations.AddField(
            model_name='bandpost',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band_answers', to=settings.AUTH_USER_MODEL, verbose_name='답변자'),
        ),
    ]
