# Generated by Django 5.2.8 on 2026-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0019_add_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='region',
            field=models.CharField(choices=[('all', '전체'), ('capital', '수도권'), ('busan', '영남권'), ('daegu', '대구권'), ('gwangju', '호남권'), ('daejeon', '충청권'), ('ulsan', '울산권'), ('gangwon', '강원권'), ('jeju', '제주권')], default='all', max_length=20, verbose_name='지역'),
        ),
    ]
