# Generated by Django 5.2.8 on 2026-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0020_alter_band_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='facility_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_address_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='상세 주소'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_amenities',
            field=models.CharField(blank=True, help_text='쉼표 구분', max_length=300, verbose_name='편의 시설'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_court_count',
            field=models.PositiveIntegerField(default=0, verbose_name='코트 수'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_operating_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='운영 시간'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='band',
            name='facility_pricing',
            field=models.CharField(blank=True, max_length=300, verbose_name='이용 요금'),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_type',
            field=models.CharField(choices=[('flash', '번개'), ('group', '모임'), ('club', '동호회'), ('center', '센터')], default='group', max_length=20, verbose_name='주요 유형'),
        ),
    ]
