# Generated by Django 5.2.8 on 2026-05-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0021_band_facility_address_band_facility_address_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='applicant_contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='등록 신청자 연락처'),
        ),
    ]
