# Generated by Django 5.2.8 on 2026-05-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0022_band_applicant_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandschedule',
            name='cost',
            field=models.IntegerField(blank=True, default=0, help_text='참가비 (원). 0 또는 비워두면 무료.', null=True, verbose_name='참가비'),
        ),
    ]
