# Generated by Django 5.2.8 on 2026-06-15 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0023_bandschedule_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '진행중'), ('ended', '종료')], default='active', max_length=10)),
                ('discipline_mode', models.CharField(choices=[('mixed_only', '혼복만'), ('singles_gender', '남복·여복만'), ('all', '전부 섞기')], default='all', max_length=20)),
                ('preset', models.CharField(choices=[('balanced', '균형파'), ('competitive', '박빙파')], default='balanced', max_length=12)),
                ('female_adjust', models.IntegerField(default=1)),
                ('court_count', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sessions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_session', to='band.bandschedule', verbose_name='번개 일정')),
            ],
            options={
                'verbose_name': '대진 세션',
                'verbose_name_plural': '대진 세션',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('mixed', '혼복'), ('mens', '남복'), ('womens', '여복')], max_length=10)),
                ('status', models.CharField(choices=[('playing', '진행중'), ('done', '종료')], default='playing', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='band.court')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='band.matchsession')),
            ],
            options={
                'verbose_name': '경기',
                'verbose_name_plural': '경기',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='band.matchsession'),
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('not_present', '미출석'), ('present', '참여중'), ('left', '퇴장')], default='not_present', max_length=12)),
                ('base_level', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('games_mixed', models.IntegerField(default=0)),
                ('games_mens', models.IntegerField(default=0)),
                ('games_womens', models.IntegerField(default=0)),
                ('last_game_ended_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='band.matchsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '대진 참가자',
                'verbose_name_plural': '대진 참가자',
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('session', 'index')},
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='band.match')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.sessionparticipant')),
            ],
            options={
                'unique_together': {('match', 'participant')},
            },
        ),
    ]
