# Generated by Django 5.2.8 on 2026-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0024_court_matchsession_match_court_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandscheduleapplication',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='당일 출석 체크인 시각. 있으면 대진 참여중, 비면 미출석/퇴장.', null=True, verbose_name='출석 체크인 시각'),
        ),
    ]
