# Generated by Django 5.2.8 on 2026-06-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0025_bandscheduleapplication_checked_in_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strict', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_p1', to='band.sessionparticipant')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_p2', to='band.sessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='band.matchsession')),
            ],
            options={
                'verbose_name': '파트너 쌍',
                'verbose_name_plural': '파트너 쌍',
            },
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strict', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests_sent', to='band.sessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to='band.matchsession')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests_received', to='band.sessionparticipant')),
            ],
            options={
                'verbose_name': '파트너 신청',
                'verbose_name_plural': '파트너 신청',
            },
        ),
    ]
