# Generated by Django 5.2.8 on 2026-06-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0026_pair_partnerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_courts', to='band.sessionparticipant'),
        ),
    ]
