# Generated by Django 5.2.8 on 2026-06-21 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0027_court_coach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(blank=True, choices=[('mixed', '혼복'), ('mens', '남복'), ('womens', '여복')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='band.matchsession')),
            ],
            options={
                'verbose_name': '예약 경기',
                'verbose_name_plural': '예약 경기',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservedMatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.sessionparticipant')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='band.reservedmatch')),
            ],
            options={
                'unique_together': {('reservation', 'participant')},
            },
        ),
    ]
