# Generated by Django 5.2.8 on 2026-06-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0029_court_name_sessionparticipant_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandschedule',
            name='region',
            field=models.CharField(blank=True, choices=[('all', '전체'), ('capital', '수도권'), ('busan', '영남권'), ('daegu', '대구권'), ('gwangju', '호남권'), ('daejeon', '충청권'), ('ulsan', '울산권'), ('gangwon', '강원권'), ('jeju', '제주권')], default='all', max_length=20, verbose_name='지역'),
        ),
    ]
