# Generated by Django 5.2.8 on 2026-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0030_bandschedule_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='region',
            field=models.CharField(choices=[('all', '전체'), ('capital', '수도권'), ('yeongnam', '영남권'), ('busan', '부산'), ('daegu', '대구'), ('honam', '호남권'), ('gwangju', '광주'), ('chungcheong', '충청권'), ('daejeon', '대전'), ('ulsan', '울산'), ('gangwon', '강원'), ('jeju', '제주')], default='all', max_length=20, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='bandschedule',
            name='region',
            field=models.CharField(blank=True, choices=[('all', '전체'), ('capital', '수도권'), ('yeongnam', '영남권'), ('busan', '부산'), ('daegu', '대구'), ('honam', '호남권'), ('gwangju', '광주'), ('chungcheong', '충청권'), ('daejeon', '대전'), ('ulsan', '울산'), ('gangwon', '강원'), ('jeju', '제주')], default='all', max_length=20, verbose_name='지역'),
        ),
    ]
