# Generated by Django 5.2.8 on 2026-07-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0031_alter_band_region_alter_bandschedule_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandscheduleapplication',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('rejected', '거부됨'), ('cancelled', '취소됨'), ('waiting', '대기(정원초과)')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
