# Generated by Django 5.2.8 on 2026-07-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0032_alter_bandscheduleapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandschedule',
            name='level_quota',
            field=models.JSONField(blank=True, default=dict, verbose_name='급수별 성별 정원'),
        ),
        migrations.AddField(
            model_name='bandschedule',
            name='use_level_quota',
            field=models.BooleanField(default=False, verbose_name='급수별 정원 사용'),
        ),
    ]
