# Generated by Django 5.2.8 on 2026-07-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0033_bandschedule_level_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandschedule',
            name='quota_by_gender',
            field=models.BooleanField(default=False, verbose_name='급수 정원 성별 구분'),
        ),
        migrations.AlterField(
            model_name='bandschedule',
            name='level_quota',
            field=models.JSONField(blank=True, default=dict, verbose_name='급수별 정원'),
        ),
    ]
