# Generated by Django 5.2.8 on 2026-07-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0034_bandschedule_quota_by_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandschedule',
            name='gender_quota',
            field=models.JSONField(blank=True, default=dict, verbose_name='성별 정원'),
        ),
        migrations.AlterField(
            model_name='bandschedule',
            name='quota_by_gender',
            field=models.BooleanField(default=False, verbose_name='정원 성별 구분'),
        ),
    ]
