# Generated by Django 5.2.8 on 2026-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0036_existing_schedules_require_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='overridden',
            field=models.BooleanField(default=False),
        ),
    ]
