# Generated by Django 5.2.8 on 2026-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0037_sessionparticipant_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsession',
            name='auto',
            field=models.BooleanField(default=True),
        ),
    ]
