# Generated by Django 5.2.8 on 2025-11-17 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('category', models.CharField(choices=[('free', '자유주제'), ('hot', 'Hot 글'), ('review', '대회 후기')], default='free', max_length=20, verbose_name='카테고리')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='댓글 수')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='고정 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요한 사용자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='좋아요한 사용자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment', verbose_name='부모 댓글')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/post_images/%Y/%m/%d/', verbose_name='이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 이미지',
                'verbose_name_plural': '게시글 이미지',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='공유일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='community.post', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to=settings.AUTH_USER_MODEL, verbose_name='공유한 사용자')),
            ],
            options={
                'verbose_name': '게시글 공유',
                'verbose_name_plural': '게시글 공유',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='community_p_created_6febb2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='community_p_categor_0dbe3e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='community_p_author__5261da_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_bea033_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='community_c_author__1e6995_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='community_c_parent__5a3862_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'order'], name='community_p_post_id_b89cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['post'], name='community_p_post_id_1686b9_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['user'], name='community_p_user_id_f8f7f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postshare',
            unique_together={('post', 'user')},
        ),
    ]
