# Generated by Django 5.2.8 on 2025-11-19 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_categories_and_migrate_data(apps, schema_editor):
    """Category 생성 및 초기 데이터 추가"""
    Category = apps.get_model('community', 'Category')
    
    categories = [
        {'name': 'Hot 글', 'slug': 'hot', 'display_order': 1, 'is_active': True},
        {'name': '자유주제', 'slug': 'free', 'display_order': 2, 'is_active': True},
        {'name': '대회 후기', 'slug': 'review', 'display_order': 3, 'is_active': True},
    ]
    
    for category_data in categories:
        Category.objects.get_or_create(
            slug=category_data['slug'],
            defaults=category_data
        )


def copy_category_to_old_category(apps, schema_editor):
    """기존 category 값을 _old_category로 복사 (SQL 사용)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE community_post SET _old_category = category WHERE category IS NOT NULL"
        )


def migrate_post_categories_forward(apps, schema_editor):
    """기존 Post의 category CharField 값을 Category ForeignKey로 마이그레이션"""
    Post = apps.get_model('community', 'Post')
    Category = apps.get_model('community', 'Category')
    
    # 카테고리 매핑 (slug 기반)
    category_map = {}
    for slug in ['hot', 'free', 'review']:
        try:
            category = Category.objects.get(slug=slug)
            category_map[slug] = category
        except Category.DoesNotExist:
            pass
    
    # 기존 Post 데이터의 category 마이그레이션
    for post in Post.objects.all():
        old_category = getattr(post, '_old_category', None)
        if old_category and old_category in category_map:
            post.category = category_map[old_category]
            post.save(update_fields=['category'])


def migrate_post_categories_reverse(apps, schema_editor):
    """롤백 시 처리"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Category 모델 생성
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(help_text='URL에 사용될 고유 식별자', unique=True, verbose_name='슬러그')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='작은 숫자일수록 먼저 표시됩니다', verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['display_order', 'name'],
            },
        ),
        # 2. 초기 카테고리 데이터 생성
        migrations.RunPython(create_categories_and_migrate_data, migrations.RunPython.noop),
        # 3. 기존 category 값을 임시 필드로 저장하기 위해 임시 필드 추가
        migrations.AddField(
            model_name='post',
            name='_old_category',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
        # 4. 기존 category 값을 _old_category로 복사
        migrations.RunPython(copy_category_to_old_category, migrations.RunPython.noop),
        # 5. 인덱스 제거
        migrations.RemoveIndex(
            model_name='post',
            name='community_p_categor_0dbe3e_idx',
        ),
        # 6. category 필드를 ForeignKey로 변경
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.category', verbose_name='카테고리'),
        ),
        # 7. _old_category 값을 기반으로 category ForeignKey 설정
        migrations.RunPython(migrate_post_categories_forward, migrate_post_categories_reverse),
        # 8. 임시 필드 제거
        migrations.RemoveField(
            model_name='post',
            name='_old_category',
        ),
        # 9. 인덱스 추가
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='community_c_slug_777ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'display_order'], name='community_c_is_acti_5c99dc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-created_at'], name='community_p_categor_d5bd82_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-view_count'], name='community_p_view_co_b34b52_idx'),
        ),
    ]
