# Generated by Django 5.2.8 on 2025-11-19 09:49

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """초기 카테고리 데이터 생성 및 기존 Post 데이터 마이그레이션"""
    Category = apps.get_model('community', 'Category')
    Post = apps.get_model('community', 'Post')
    
    categories = [
        {'name': 'Hot 글', 'slug': 'hot', 'display_order': 1, 'is_active': True},
        {'name': '자유주제', 'slug': 'free', 'display_order': 2, 'is_active': True},
        {'name': '대회 후기', 'slug': 'review', 'display_order': 3, 'is_active': True},
    ]
    
    # 카테고리 생성
    category_map = {}
    for category_data in categories:
        category, created = Category.objects.get_or_create(
            slug=category_data['slug'],
            defaults=category_data
        )
        category_map[category_data['slug']] = category
    
    # 주의: 0002 마이그레이션에서 이미 category 필드가 ForeignKey로 변경되었으므로
    # 기존 CharField 값은 사라졌을 수 있습니다. 
    # 만약 기존 데이터가 있다면, 수동으로 카테고리를 할당해야 합니다.


def reverse_create_initial_categories(apps, schema_editor):
    """마이그레이션 롤백 시 카테고리 삭제"""
    Category = apps.get_model('community', 'Category')
    Category.objects.filter(slug__in=['hot', 'free', 'review']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_category_remove_post_community_p_categor_0dbe3e_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_create_initial_categories),
    ]
