# Generated by Django 5.2.8 on 2025-11-19 10:22

from django.db import migrations, models
import django.db.models.deletion


def migrate_category_to_foreignkey(apps, schema_editor):
    """category_id varchar를 ForeignKey로 변환"""
    Post = apps.get_model('community', 'Post')
    Category = apps.get_model('community', 'Category')
    
    # 카테고리 매핑 (slug -> id)
    category_map = {}
    for category in Category.objects.all():
        category_map[category.slug] = category.id
    
    # 기존 Post 데이터의 category 마이그레이션
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 모든 Post를 가져와서 category_id를 업데이트
        cursor.execute("SELECT id, category_id FROM community_post WHERE category_id IS NOT NULL")
        posts = cursor.fetchall()
        
        for post_id, old_category_slug in posts:
            if old_category_slug in category_map:
                new_category_id = category_map[old_category_slug]
                cursor.execute(
                    "UPDATE community_post SET category_id = %s WHERE id = %s",
                    [new_category_id, post_id]
                )
            else:
                # 매핑되지 않은 경우 NULL로 설정
                cursor.execute(
                    "UPDATE community_post SET category_id = NULL WHERE id = %s",
                    [post_id]
                )


def reverse_migrate_category(apps, schema_editor):
    """롤백 시 처리"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_create_initial_categories'),
    ]

    operations = [
        # 1. 데이터 마이그레이션 (문자열 -> ID)
        migrations.RunPython(migrate_category_to_foreignkey, reverse_migrate_category),
        # 2. category_id를 integer로 변경하고 ForeignKey로 설정
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.category', verbose_name='카테고리'),
        ),
    ]
