# Generated by Django 5.2.8 on 2025-12-14 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_fix_category_foreignkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('community', '커뮤니티'), ('badmintok', '배드민톡')], default='community', max_length=20, verbose_name='출처'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source', '-created_at'], name='community_p_source_ece6fc_idx'),
        ),
    ]
