# Generated by Django 5.2.8 on 2025-12-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_post_source_post_community_p_source_ece6fc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('community', '커뮤니티'), ('badmintok', '배드민톡'), ('member_reviews', '동호인 리뷰')], default='community', max_length=20, verbose_name='출처'),
        ),
    ]
