# Generated by Django 5.2.8 on 2025-12-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_post_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintokPost',
            fields=[
            ],
            options={
                'verbose_name': '배드민톡 게시글',
                'verbose_name_plural': '배드민톡 게시글',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('community.post',),
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 게시글',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('community.post',),
        ),
    ]
