# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations


def create_badmintok_categories(apps, schema_editor):
    """배드민톡 카테고리 데이터 생성"""
    Category = apps.get_model('community', 'Category')
    
    # 배드민톡 카테고리 정의
    categories = [
        # 뉴스 탭 카테고리
        {'name': '대회 소식', 'slug': 'tournament', 'display_order': 10, 'is_active': True},
        {'name': '선수 소식', 'slug': 'player', 'display_order': 11, 'is_active': True},
        {'name': '장비 뉴스', 'slug': 'equipment', 'display_order': 12, 'is_active': True},
        {'name': '동호인 소식', 'slug': 'community', 'display_order': 13, 'is_active': True},
        
        # 리뷰 탭 카테고리
        {'name': '라켓', 'slug': 'racket', 'display_order': 20, 'is_active': True},
        {'name': '신발/가방', 'slug': 'shoes', 'display_order': 21, 'is_active': True},
        {'name': '의류', 'slug': 'apparel', 'display_order': 22, 'is_active': True},
        {'name': '셔틀콕', 'slug': 'shuttlecock', 'display_order': 23, 'is_active': True},
        {'name': '보호대', 'slug': 'protective', 'display_order': 24, 'is_active': True},
        {'name': '기타/용품', 'slug': 'accessories', 'display_order': 25, 'is_active': True},
        
        # 브랜드관 탭 카테고리
        {'name': '요넥스', 'slug': 'yonex', 'display_order': 30, 'is_active': True},
        {'name': '리닝', 'slug': 'lining', 'display_order': 31, 'is_active': True},
        {'name': '빅터', 'slug': 'victor', 'display_order': 32, 'is_active': True},
        {'name': '미즈노', 'slug': 'mizuno', 'display_order': 33, 'is_active': True},
        {'name': '테크니스트', 'slug': 'technist', 'display_order': 34, 'is_active': True},
        {'name': '스트로커스', 'slug': 'strokus', 'display_order': 35, 'is_active': True},
        {'name': '레드선', 'slug': 'redsun', 'display_order': 36, 'is_active': True},
        {'name': '트라이온', 'slug': 'trion', 'display_order': 37, 'is_active': True},
        {'name': '트리코어', 'slug': 'tricore', 'display_order': 38, 'is_active': True},
        {'name': '아펙스', 'slug': 'apacs', 'display_order': 39, 'is_active': True},
    ]
    
    # 카테고리 생성 (이미 존재하면 건너뛰기)
    for category_data in categories:
        Category.objects.get_or_create(
            slug=category_data['slug'],
            defaults=category_data
        )


def reverse_create_badmintok_categories(apps, schema_editor):
    """마이그레이션 롤백 시 배드민톡 카테고리 삭제"""
    Category = apps.get_model('community', 'Category')
    badmintok_slugs = [
        'tournament', 'player', 'equipment', 'community',
        'racket', 'shoes', 'apparel', 'shuttlecock', 'protective', 'accessories',
        'yonex', 'lining', 'victor', 'mizuno', 'technist', 'strokus', 'redsun', 'trion', 'tricore', 'apacs'
    ]
    Category.objects.filter(slug__in=badmintok_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_badmintokpost_communitypost'),
    ]

    operations = [
        migrations.RunPython(create_badmintok_categories, reverse_create_badmintok_categories),
    ]
