# Generated by Django 5.2.8 on 2025-12-18 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_create_badmintok_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitypost',
            options={'verbose_name': '동호인톡 게시글', 'verbose_name_plural': '동호인톡 게시글'},
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='예약 발행 시간 설정 (비어있으면 즉시 발행)', null=True, verbose_name='발행 일시'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL에 사용될 고유 식별자 (한글 가능)', max_length=200, verbose_name='슬러그'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='게시글 썸네일 이미지', null=True, upload_to='community/thumbnails/%Y/%m/%d/', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('community', '동호인톡'), ('badmintok', '배드민톡'), ('member_reviews', '동호인 리뷰')], default='community', max_length=20, verbose_name='출처'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='community_p_slug_614d88_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['published_at'], name='community_p_publish_9a7d6d_idx'),
        ),
    ]
