# Generated by Django 5.2.8 on 2025-12-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_communitypost_options_post_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='상위 카테고리를 선택하세요 (최상위인 경우 비워두세요)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='community.category', verbose_name='상위 카테고리'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='community_c_parent__eb9340_idx'),
        ),
    ]
