# Generated by Django 5.2.8 on 2025-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='SEO 최적화를 위한 포커스 키워드', max_length=100, verbose_name='포커스 키워드'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='임시저장 글은 공개되지 않습니다', verbose_name='임시저장'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='검색 엔진에 표시될 설명 (160자 이내 권장)', max_length=160, verbose_name='메타 설명'),
        ),
    ]
