# Generated by Django 5.2.8 on 2025-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_post_focus_keyword_post_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_alt',
            field=models.CharField(blank=True, help_text='썸네일 이미지의 Alt 텍스트', max_length=200, verbose_name='썸네일 대체 텍스트'),
        ),
    ]
