# Generated by Django 5.2.8 on 2025-12-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_post_thumbnail_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL에 사용될 고유 식별자 (한글 가능)', max_length=45, verbose_name='슬러그'),
        ),
    ]
