# Generated by Django 5.2.8 on 2025-12-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='여러 카테고리 선택 가능', related_name='posts_multi', to='community.category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.category', verbose_name='메인 카테고리'),
        ),
    ]
