# Generated by Django 5.2.8 on 2025-12-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_post_categories_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='탭 이름')),
                ('slug', models.SlugField(help_text='URL에 사용될 고유 식별자', verbose_name='슬러그')),
                ('source', models.CharField(choices=[('community', '동호인톡'), ('badmintok', '배드민톡')], help_text='배드민톡 또는 동호인톡', max_length=20, verbose_name='출처')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='작은 숫자일수록 먼저 표시됩니다', verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(help_text='이 탭에서 표시할 카테고리', on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='community.category', verbose_name='연결된 카테고리')),
            ],
            options={
                'verbose_name': '탭',
                'verbose_name_plural': '탭',
                'ordering': ['source', 'display_order', 'name'],
                'indexes': [models.Index(fields=['source', 'is_active', 'display_order'], name='community_t_source_b1e3ec_idx'), models.Index(fields=['slug', 'source'], name='community_t_slug_61294a_idx')],
                'unique_together': {('slug', 'source')},
            },
        ),
    ]
