# Generated by Django 5.2.8 on 2025-12-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='category',
            field=models.ForeignKey(blank=True, help_text='이 탭에서 표시할 카테고리 (선택사항)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='community.category', verbose_name='연결된 카테고리'),
        ),
    ]
