# Generated by Django 5.2.8 on 2025-12-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_alter_tab_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadmintokPost',
        ),
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': [],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('community.category',),
        ),
        migrations.CreateModel(
            name='CommunityTab',
            fields=[
            ],
            options={
                'verbose_name': '탭',
                'verbose_name_plural': '탭',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('community.tab',),
        ),
        migrations.AlterModelOptions(
            name='communitypost',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='community_c_is_acti_5c99dc_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.CharField(choices=[('community', '동호인톡'), ('badmintok', '배드민톡')], default='community', help_text='배드민톡 또는 동호인톡', max_length=20, verbose_name='출처'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['source', 'is_active', 'display_order'], name='community_c_source_78056f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['source', 'parent'], name='community_c_source_be63c9_idx'),
        ),
    ]
