# Generated by Django 5.2.8 on 2025-12-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_add_source_to_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tab',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tab',
            name='category',
        ),
        migrations.DeleteModel(
            name='CommunityTab',
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
