# Generated by Django 5.2.8 on 2026-02-05 13:07

import badmintok.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_fix_badmintok_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=badmintok.fields.WebPImageField(blank=True, help_text='게시글 썸네일 이미지', null=True, upload_to='community/thumbnails/%Y/%m/%d/', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=badmintok.fields.WebPImageField(upload_to='community/post_images/%Y/%m/%d/', verbose_name='이미지'),
        ),
    ]
