# Generated by Django 5.2.8 on 2026-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_alter_post_thumbnail_alter_postimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그명')),
                ('slug', models.SlugField(help_text='URL에 사용될 식별자', verbose_name='슬러그')),
                ('source', models.CharField(choices=[('community', '동호인톡'), ('badmintok', '배드민톡')], default='badmintok', max_length=20, verbose_name='출처')),
                ('description', models.CharField(blank=True, help_text='태그 아카이브 페이지의 SEO meta description', max_length=200, verbose_name='설명')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['source', 'is_active', 'display_order'], name='community_t_source_32d403_idx'), models.Index(fields=['slug'], name='community_t_slug_830be2_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'slug'), name='uniq_tag_source_slug')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='브랜드 등 교차 분류 태그', related_name='posts', to='community.tag', verbose_name='태그'),
        ),
    ]
