# Generated by Django 5.2.8 on 2025-11-10 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='프로필 사진')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='이름')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성'), ('other', '기타'), ('unknown', '선택 안 함')], default='unknown', max_length=10, verbose_name='성별')),
                ('age_range', models.CharField(blank=True, max_length=50, verbose_name='연령대')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='출생연도')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('shipping_receiver', models.CharField(blank=True, max_length=100, verbose_name='수령인명')),
                ('shipping_phone_number', models.CharField(blank=True, max_length=20, verbose_name='배송지 전화번호')),
                ('shipping_address', models.TextField(blank=True, verbose_name='배송지 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
