# Generated by Django 5.2.8 on 2025-11-10 12:04

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/userprofile/user.png', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/', location=pathlib.PureWindowsPath('C:/Users/home/Documents/project/badmintok_sever/badmintok/static')), upload_to='images/userprofile/', verbose_name='프로필 사진'),
        ),
    ]
