# Generated by Django 5.2.8 on 2025-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, help_text='소셜 로그인 제공자 (kakao, google 등). 일반 회원가입은 비어있음.', max_length=20, null=True, verbose_name='인증 제공자'),
        ),
    ]
