# Generated by Django 5.2.8 on 2025-12-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='band_creation_blocked_until',
            field=models.DateTimeField(blank=True, help_text='이 일시까지 모임을 생성할 수 없습니다.', null=True, verbose_name='모임 생성 제한 일시'),
        ),
    ]
