# Generated by Django 5.2.8 on 2025-12-21 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_band_creation_blocked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', '일반 문의'), ('technical', '기술 문의'), ('bug', '버그 신고'), ('suggestion', '건의사항'), ('other', '기타')], default='general', max_length=20, verbose_name='문의 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('answered', '답변완료'), ('closed', '종료')], default='pending', max_length=20, verbose_name='상태')),
                ('admin_response', models.TextField(blank=True, verbose_name='관리자 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='문의일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='답변자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='문의자')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_in_user_id_ba6a9d_idx'), models.Index(fields=['status'], name='accounts_in_status_b3a7cf_idx'), models.Index(fields=['-created_at'], name='accounts_in_created_fa689f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('user', '사용자'), ('post', '게시글'), ('comment', '댓글'), ('band', '모임'), ('other', '기타')], max_length=20, verbose_name='신고 유형')),
                ('target_id', models.PositiveIntegerField(help_text='신고 대상의 ID', verbose_name='대상 ID')),
                ('reason', models.TextField(verbose_name='신고 사유')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('reviewing', '검토중'), ('resolved', '처리완료'), ('rejected', '기각')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reports', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고',
                'indexes': [models.Index(fields=['reporter'], name='accounts_re_reporte_8da0cd_idx'), models.Index(fields=['report_type', 'target_id'], name='accounts_re_report__eda831_idx'), models.Index(fields=['status'], name='accounts_re_status_859365_idx'), models.Index(fields=['-created_at'], name='accounts_re_created_08a081_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='차단일')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='차단당한 사용자')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='차단한 사용자')),
            ],
            options={
                'verbose_name': '사용자 차단',
                'verbose_name_plural': '사용자 차단',
                'indexes': [models.Index(fields=['blocker'], name='accounts_us_blocker_47e452_idx'), models.Index(fields=['blocked'], name='accounts_us_blocked_8e644c_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
