# Generated by Django 5.2.8 on 2026-01-09 15:59

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badminton_level',
            field=models.CharField(blank=True, choices=[('1', '1급'), ('2', '2급'), ('3', '3급'), ('4', '4급'), ('5', '5급'), ('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급'), ('', '미입력')], default='', help_text='배드민턴 실력 급수', max_length=20, verbose_name='배드민턴 급수'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/userprofile/user.png', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PureWindowsPath('C:/Users/home/Documents/project/badmintok_sever/badmintok/media')), upload_to='images/userprofile/', verbose_name='프로필 사진'),
        ),
    ]
