# Generated by Django 5.2.8 on 2026-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_badminton_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badminton_level',
            field=models.CharField(blank=True, choices=[('beginner', '왕초심'), ('d', 'D'), ('c', 'C'), ('b', 'B'), ('a', 'A'), ('s', 'S'), ('master', '자강'), ('', '미입력')], default='', help_text='배드민턴 실력 급수', max_length=20, verbose_name='배드민턴 급수'),
        ),
    ]
