# Generated by Django 5.2.8 on 2026-01-12 11:26

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_badminton_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/userprofile/user.png', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PurePosixPath('/Users/ordinary/Documents/project/badmintok/media')), upload_to='images/userprofile/', verbose_name='프로필 사진'),
        ),
    ]
