# Generated by Django 5.2.8 on 2026-02-05 13:07

import badmintok.fields
import django.core.files.storage
import pathlib
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=badmintok.fields.WebPImageField(blank=True, default='images/userprofile/user.png', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location=pathlib.PurePosixPath('/Users/ordinary/Documents/Documents/project/badmintok/media')), upload_to='images/userprofile/', verbose_name='프로필 사진'),
        ),
    ]
