# Generated by Django 5.2.8 on 2025-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintokBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='배너 제목')),
                ('image', models.ImageField(upload_to='badmintok_banners/', verbose_name='배너 이미지')),
                ('link_url', models.URLField(blank=True, verbose_name='링크 URL')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='대체 텍스트')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='숫자가 낮을수록 먼저 노출됩니다.', verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '배드민톡 배너',
                'verbose_name_plural': '배드민톡 배너',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
