# Generated by Django 5.2.8 on 2025-12-26 09:52

import badmintok.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badmintokbanner',
            name='image',
            field=models.ImageField(upload_to=badmintok.models.badmintok_banner_upload_to, verbose_name='배너 이미지'),
        ),
    ]
