# Generated by Django 5.2.8 on 2026-01-05 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0003_alter_badmintokbanner_image'),
        ('community', '0020_fix_badmintok_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintokCategory',
            fields=[
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': [],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('community.category',),
        ),
        migrations.CreateModel(
            name='BadmintokPost',
            fields=[
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('community.post',),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='세션 키')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('url_path', models.CharField(db_index=True, max_length=500, verbose_name='URL 경로')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='페이지 제목')),
                ('referer', models.CharField(blank=True, help_text='유입 경로', max_length=500, verbose_name='리퍼러')),
                ('referer_domain', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='리퍼러 도메인')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('device_type', models.CharField(choices=[('desktop', '데스크톱'), ('mobile', '모바일'), ('tablet', '태블릿'), ('bot', '봇')], default='desktop', max_length=20, verbose_name='디바이스 유형')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='방문 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '방문 로그',
                'verbose_name_plural': '방문 로그',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='badmintok_v_visited_fd5d20_idx'), models.Index(fields=['session_key', '-visited_at'], name='badmintok_v_session_8df0a6_idx'), models.Index(fields=['url_path', '-visited_at'], name='badmintok_v_url_pat_e77f7d_idx'), models.Index(fields=['referer_domain', '-visited_at'], name='badmintok_v_referer_e11646_idx')],
            },
        ),
    ]
