# Generated by Django 5.2.8 on 2026-01-11 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0004_badmintokcategory_badmintokpost_visitorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='세션 키')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('destination_url', models.URLField(max_length=1000, verbose_name='목적지 URL')),
                ('destination_domain', models.CharField(db_index=True, max_length=200, verbose_name='목적지 도메인')),
                ('link_text', models.CharField(blank=True, help_text='링크에 표시된 텍스트', max_length=200, verbose_name='링크 텍스트')),
                ('link_type', models.CharField(choices=[('banner', '배너'), ('text_link', '텍스트 링크'), ('button', '버튼'), ('other', '기타')], default='text_link', max_length=50, verbose_name='링크 유형')),
                ('source_url', models.CharField(help_text='클릭이 발생한 페이지', max_length=500, verbose_name='소스 URL')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('device_type', models.CharField(choices=[('desktop', '데스크톱'), ('mobile', '모바일'), ('tablet', '태블릿')], default='desktop', max_length=20, verbose_name='디바이스 유형')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='클릭 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_clicks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '외부 링크 클릭',
                'verbose_name_plural': '외부 링크 클릭',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['-clicked_at'], name='badmintok_o_clicked_501909_idx'), models.Index(fields=['destination_domain', '-clicked_at'], name='badmintok_o_destina_f00533_idx'), models.Index(fields=['link_type', '-clicked_at'], name='badmintok_o_link_ty_fdf783_idx')],
            },
        ),
    ]
