# Generated by Django 5.2.8 on 2026-02-04 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0005_outboundclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outboundclick',
            index=models.Index(fields=['device_type', '-clicked_at'], name='badmintok_o_device__96c399_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['device_type', '-visited_at'], name='badmintok_v_device__976598_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['-visited_at', 'device_type'], name='badmintok_v_visited_12fd87_idx'),
        ),
    ]
