# Generated by Django 5.2.8 on 2026-02-05 13:07

import badmintok.fields
import badmintok.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0006_add_statistics_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badmintokbanner',
            name='image',
            field=badmintok.fields.WebPImageField(upload_to=badmintok.models.badmintok_banner_upload_to, verbose_name='배너 이미지'),
        ),
    ]
