# Generated by Django 5.2.8 on 2026-02-06 12:15

import badmintok.fields
import badmintok.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0007_alter_badmintokbanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('mobile_image', badmintok.fields.WebPImageField(help_text='권장 비율: 16:9 또는 앱에서 사용하는 비율', upload_to=badmintok.models.banner_mobile_image_upload_to, verbose_name='모바일 이미지')),
                ('link_url', models.URLField(blank=True, help_text='클릭 시 이동할 URL (선택)', verbose_name='클릭 시 이동 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.PositiveIntegerField(default=0, help_text='숫자가 낮을수록 먼저 노출됩니다.', verbose_name='정렬 순서')),
                ('start_date', models.DateField(blank=True, help_text='비워두면 즉시 노출', null=True, verbose_name='노출 시작일')),
                ('end_date', models.DateField(blank=True, help_text='비워두면 무기한 노출', null=True, verbose_name='노출 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
