# Generated by Django 5.2.8 on 2026-04-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0008_add_banner_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='영상 제목')),
                ('youtube_url', models.URLField(verbose_name='유튜브 URL')),
                ('video_id', models.CharField(blank=True, max_length=20, verbose_name='YouTube Video ID')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='썸네일 URL')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('order', models.IntegerField(default=0, help_text='숫자가 높을수록 먼저 노출됩니다.', verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '유튜브 영상',
                'verbose_name_plural': '유튜브 영상',
                'ordering': ['-order', '-created_at'],
            },
        ),
    ]
