# Generated by Django 5.2.8 on 2026-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0009_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='유튜브 업로드일'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
