# Generated by Django 5.2.8 on 2026-05-18 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0010_youtube_video_add_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownloadClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('other', '기타')], default='other', max_length=10, verbose_name='운영체제')),
                ('referrer_path', models.CharField(blank=True, help_text='버튼을 누른 페이지 경로', max_length=200, verbose_name='유입 경로')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='클릭 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_download_clicks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '앱 다운로드 클릭',
                'verbose_name_plural': '앱 다운로드 클릭',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['os', '-created_at'], name='badmintok_a_os_e4afe0_idx')],
            },
        ),
    ]
