# Generated by Django 5.2.8 on 2026-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0011_appdownloadclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='app_version',
            field=models.CharField(blank=True, max_length=30, verbose_name='앱 버전'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='source',
            field=models.CharField(choices=[('web', '웹'), ('app', '앱')], db_index=True, default='web', max_length=10, verbose_name='출처'),
        ),
    ]
