# Generated by Django 5.2.8 on 2026-06-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintok', '0012_visitorlog_app_version_visitorlog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='응답 코드'),
        ),
    ]
