# Generated by Django 5.2.8 on 2026-04-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0019_add_faq_answer'),
        ('community', '0021_alter_post_thumbnail_alter_postimage_image'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='band.band', verbose_name='관련 밴드'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_band_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='band.bandschedule', verbose_name='관련 밴드 일정'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_community_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.post', verbose_name='관련 커뮤니티 게시글'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment', '댓글'), ('reply', '답글'), ('notice', '공지사항'), ('band', '모임'), ('schedule', '일정'), ('application', '참가신청'), ('membership', '가입'), ('like', '좋아요')], max_length=20, verbose_name='알림 유형'),
        ),
    ]
