# Generated by Django 5.2.8 on 2026-04-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment', '댓글'), ('reply', '답글'), ('notice', '공지사항'), ('band', '모임'), ('schedule', '일정'), ('schedule_notice', '일정 알림'), ('application', '참가신청'), ('membership', '가입'), ('like', '좋아요')], max_length=20, verbose_name='알림 유형'),
        ),
    ]
