# Generated by Django 5.2.8 on 2026-06-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_user_date_joined_idx'),
        ('notifications', '0006_alter_device_token_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.inquiry', verbose_name='관련 문의'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment', '댓글'), ('reply', '답글'), ('notice', '공지사항'), ('band', '모임'), ('schedule', '일정'), ('schedule_notice', '일정 알림'), ('application', '참가신청'), ('membership', '가입'), ('like', '좋아요'), ('badmintok_post', '배드민톡 새 글'), ('inquiry', '문의 답변')], max_length=20, verbose_name='알림 유형'),
        ),
    ]
