# Generated by Django 5.2.8 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_related_inquiry_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment', '댓글'), ('reply', '답글'), ('notice', '공지사항'), ('band', '모임'), ('schedule', '일정'), ('schedule_notice', '일정 알림'), ('application', '참가신청'), ('membership', '가입'), ('like', '좋아요'), ('badmintok_post', '배드민톡 새 글'), ('inquiry', '문의 답변'), ('match_next_game', '다음 경기'), ('partner_request', '파트너 신청'), ('partner_approved', '파트너 확정')], max_length=20, verbose_name='알림 유형'),
        ),
    ]
