"""
Django settings for badmintok project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-sspxl=1jonty09c+iave54)vi=uis7yv!r%7f0kd1+cw4bq@sr')

# SECURITY WARNING: don't run with debug turned on in production!
# 환경 변수가 없으면 기본적으로 DEBUG=True (로컬 개발 환경)
# Docker 환경에서는 환경 변수로 명시적으로 설정
DEBUG_ENV = os.environ.get('DJANGO_DEBUG', '')
if DEBUG_ENV:
    DEBUG = DEBUG_ENV.lower() == 'true'
else:
    # 환경 변수가 없으면 로컬 개발 환경으로 간주하고 DEBUG=True
    DEBUG = True

# ALLOWED_HOSTS 설정
ALLOWED_HOSTS_ENV = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]
    # healthcheck를 위해 localhost와 127.0.0.1 항상 추가
    if 'localhost' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('localhost')
    if '127.0.0.1' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('127.0.0.1')
else:
    # 개발 환경 기본값: 모든 호스트 허용 + 내부 컨테이너 이름
    ALLOWED_HOSTS = ['*', 'badmintok-web', 'badmintok-web-prod', 'localhost', '127.0.0.1']

# Nginx 프록시를 통한 요청 처리
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# HTTPS 사용 시 설정 (프로덕션)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Nginx에서 처리하므로 False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # CSRF Trusted Origins 설정 (배포 도메인 추가)
    CSRF_TRUSTED_ORIGINS_ENV = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    if CSRF_TRUSTED_ORIGINS_ENV:
        CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(',')]
    else:
        # 기본값 (실제 배포 도메인으로 변경 필요)
        CSRF_TRUSTED_ORIGINS = ['https://badmintok.com', 'https://www.badmintok.com']
else:
    SECURE_PROXY_SSL_HEADER = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.syndication',
    # Third-party apps
    'corsheaders',
    'rest_framework',
    # 프로젝트 앱
    'badmintok.apps.BadmintokConfig',
    # 도메인 앱
    'accounts',
    'contests',
    'community',
    'band',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware는 CommonMiddleware 전에 위치
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'badmintok.middleware.VisitorTrackingMiddleware',  # 방문자 추적
]

ROOT_URLCONF = 'badmintok.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'badmintok.context_processors.community_categories',
                'accounts.context_processors.social_login_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'badmintok.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # MYSQL을 사용함
        'NAME': os.environ.get('DB_NAME', 'badmintok'),        # 데이터베이스(스키마) 이름
        'USER': os.environ.get('DB_USER', 'root'),             # 데이터베이스(접속명) 사용자 이름
        'PASSWORD': os.environ.get('DB_PASSWORD', '1234'),     # 데이터베이스 비밀번호
        # Docker 환경에서는 서비스 이름(예: db)을 호스트로 사용
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),        # 데이터베이스 호스트
        'PORT': os.environ.get('DB_PORT', '3306'),             # 데이터베이스 포트
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 정적 파일 URL
STATIC_URL = '/static/'

# collectstatic이 모으는 최종 위치 (Docker/Nginx 등에서 서빙)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 개발 환경에서만 추가로 읽어올 정적 파일 경로
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
# 전체 요청 크기 제한 (이미지 + 폼 데이터 포함)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB (이미지 + 폼 데이터를 고려하여 여유있게 설정)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB (개별 파일 크기 제한)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# 보안 설정
if not DEBUG:
    # 프로덕션 보안 설정
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    CSRF_COOKIE_HTTPONLY = False  # JavaScript에서 CSRF 토큰 접근 가능하도록 설정
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # 로깅 설정
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'django.request': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': False,
            },
        },
    }

# 세션 설정
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # 'Lax'로 설정하여 외부 리다이렉트에서도 쿠키 전달
SESSION_SAVE_EVERY_REQUEST = True
# 프로덕션 환경에서 Nginx 프록시를 통한 세션 유지
SESSION_COOKIE_DOMAIN = None  # None으로 설정하여 모든 도메인에서 쿠키 전달
SESSION_COOKIE_PATH = '/'  # 모든 경로에서 쿠키 전달
# 세션 쿠키 이름 (기본값 사용)
SESSION_COOKIE_NAME = 'sessionid'
# SESSION_COOKIE_SECURE는 위에서 DEBUG에 따라 설정됨

KAKAO_CLIENT_ID = os.environ.get('KAKAO_REST_API_KEY', '90b3d0426d0273b8e9d1113e6184ba6a')
KAKAO_CLIENT_SECRET = os.environ.get('KAKAO_CLIENT_SECRET', '')
KAKAO_JAVASCRIPT_KEY = os.environ.get('KAKAO_JAVASCRIPT_KEY', 'd371bd2ec21840433003759185c1fbe5')
# 카카오 리다이렉트 URI
KAKAO_REDIRECT_URI = os.environ.get('KAKAO_REDIRECT_URI', 'http://localhost/accounts/kakao')

# 네이버 OAuth 설정
NAVER_CLIENT_ID = os.environ.get('NAVER_CLIENT_ID', '')
NAVER_CLIENT_SECRET = os.environ.get('NAVER_CLIENT_SECRET', '')
NAVER_REDIRECT_URI = os.environ.get('NAVER_REDIRECT_URI', 'http://localhost/accounts/naver')

# 구글 OAuth 설정
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = os.environ.get('GOOGLE_REDIRECT_URI', 'http://localhost/accounts/google')

# CORS 설정
# 환경에 따라 동적으로 설정
if DEBUG:
    # 로컬 개발 환경: localhost와 127.0.0.1에서 모든 요청 허용
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://localhost:8000',
        'http://127.0.0.1:3000',
        'http://127.0.0.1:8000',
    ]
    CORS_ALLOW_ALL_ORIGINS = True  # 개발 환경에서는 모든 origin 허용
else:
    # 프로덕션 환경: 실제 도메인만 허용
    CORS_ALLOWED_ORIGINS_ENV = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    if CORS_ALLOWED_ORIGINS_ENV:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV.split(',')]
    else:
        CORS_ALLOWED_ORIGINS = [
            'https://badmintok.com',
            'https://www.badmintok.com',
        ]
    CORS_ALLOW_ALL_ORIGINS = False

# CORS 추가 설정
CORS_ALLOW_CREDENTIALS = True  # 쿠키 전달 허용
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework 설정
REST_FRAMEWORK = {
    # 기본 인증 클래스
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # 기본 권한 클래스
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 페이지네이션
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # 렌더러
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # 파서
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # 예외 핸들러
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    # 날짜/시간 형식
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}
