# Generated by Django 5.2.8 on 2026-05-21 12:59

import badmintok.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='센터명')),
                ('region', models.CharField(choices=[('all', '전체'), ('capital', '수도권'), ('busan', '영남권'), ('daegu', '대구권'), ('gwangju', '호남권'), ('daejeon', '충청권'), ('ulsan', '울산권'), ('gangwon', '강원권'), ('jeju', '제주권')], db_index=True, default='all', max_length=20, verbose_name='지역')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='전화번호')),
                ('description', models.TextField(blank=True, verbose_name='센터 소개')),
                ('operating_hours', models.CharField(blank=True, help_text='예: 평일 06:00-23:00 / 주말 08:00-22:00', max_length=200, verbose_name='운영 시간')),
                ('pricing', models.CharField(blank=True, help_text='예: 1시간 ₩10,000', max_length=300, verbose_name='요금 정보')),
                ('court_count', models.PositiveIntegerField(default=0, verbose_name='코트 수')),
                ('amenities', models.CharField(blank=True, help_text='쉼표 구분: 샤워실, 락커, 주차장', max_length=300, verbose_name='편의 시설')),
                ('cover_image', badmintok.fields.WebPImageField(blank=True, null=True, upload_to='centers/', verbose_name='커버 이미지')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='해제하면 목록/상세 모두 비공개', verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '배드민턴 센터',
                'verbose_name_plural': '배드민턴 센터',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['region', 'is_published', '-created_at'], name='centers_cen_region_fc5f13_idx')],
            },
        ),
        migrations.CreateModel(
            name='CenterBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='centers.center', verbose_name='센터')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '센터 북마크',
                'verbose_name_plural': '센터 북마크',
                'indexes': [models.Index(fields=['user', '-created_at'], name='centers_cen_user_id_c4d518_idx'), models.Index(fields=['center', '-created_at'], name='centers_cen_center__0e8ee2_idx')],
                'unique_together': {('user', 'center')},
            },
        ),
    ]
