# Generated by Django 5.2.8 on 2026-05-21 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='address_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='상세 주소'),
        ),
        migrations.AddField(
            model_name='center',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_centers', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
    ]
