# Generated by Django 5.2.8 on 2026-05-21 22:01

import badmintok.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_address_detail_center_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='profile_image',
            field=badmintok.fields.WebPImageField(blank=True, null=True, upload_to='centers/profile/', verbose_name='프로필 이미지'),
        ),
    ]
