# Generated by Django 5.2.8 on 2026-06-18 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '센터장'), ('admin', '관리자')], default='admin', max_length=10, verbose_name='권한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='지정일')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='centers.center', verbose_name='센터')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_centers', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '센터 관리자',
                'verbose_name_plural': '센터 관리자',
                'ordering': ['-created_at'],
                'unique_together': {('center', 'user')},
            },
        ),
    ]
