# Generated by Django 5.2.8 on 2026-06-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_centermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CenterManager',
        ),
    ]
