# Generated by Django 5.2.8 on 2025-11-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='대회명')),
                ('slug', models.SlugField(help_text='URL에서 사용할 고유 값입니다.', unique=True, verbose_name='슬러그')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contest_images/', verbose_name='이미지')),
                ('schedule_start', models.DateField(verbose_name='대회 시작일')),
                ('schedule_end', models.DateField(blank=True, null=True, verbose_name='대회 종료일')),
                ('location', models.CharField(max_length=200, verbose_name='장소')),
                ('event_division', models.CharField(max_length=255, verbose_name='급수 (종목 / 연령 / 급수)')),
                ('registration_start', models.DateField(verbose_name='접수 시작일')),
                ('registration_end', models.DateField(verbose_name='접수 종료일')),
                ('entry_fee', models.CharField(blank=True, max_length=100, verbose_name='접수비')),
                ('competition_type', models.CharField(blank=True, max_length=100, verbose_name='대회구')),
                ('participant_reward', models.CharField(blank=True, max_length=255, verbose_name='참가상품')),
                ('sponsor', models.CharField(blank=True, max_length=255, verbose_name='스폰서')),
                ('award_reward', models.CharField(blank=True, max_length=255, verbose_name='입상상품')),
                ('registration_link', models.URLField(blank=True, verbose_name='접수 링크')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '전국 배드민턴 대회',
                'verbose_name_plural': '전국 배드민턴 대회',
                'ordering': ['-schedule_start', '-created_at'],
            },
        ),
    ]
