# Generated by Django 5.2.8 on 2025-11-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='분류명')),
                ('color', models.CharField(help_text='예: #31AA60', max_length=7, verbose_name='색상')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
            ],
            options={
                'verbose_name': '대회 분류',
                'verbose_name_plural': '대회 분류',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='contests.contestcategory', verbose_name='분류'),
        ),
    ]
