# Generated by Django 5.2.8 on 2025-11-12 11:39

from django.db import migrations, models


def clear_invalid_award_reward(apps, schema_editor):
    Contest = apps.get_model('contests', 'Contest')
    for contest in Contest.objects.all():
        contest.award_reward = []
        contest.save(update_fields=['award_reward'])


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestcategory_contest_category'),
    ]

    operations = [
        migrations.RunPython(clear_invalid_award_reward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contest',
            name='award_reward',
            field=models.JSONField(blank=True, help_text='JSON 형식으로 입력하세요.', null=True, verbose_name='입상상품'),
        ),
    ]
