# Generated by Django 5.2.8 on 2025-12-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_award_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_qualifying',
            field=models.BooleanField(default=False, help_text='승급 대회인 경우 체크하세요. 비승급 대회는 체크하지 않습니다.', verbose_name='승급 대회'),
        ),
    ]
