# Generated by Django 5.2.8 on 2025-12-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contest_is_qualifying'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='game_events',
            field=models.JSONField(blank=True, help_text='혼복/여복/남복 중 해당되는 항목을 선택하세요. 복수 선택 가능.', null=True, verbose_name='경기 일정(혼복/여복/남복)'),
        ),
    ]
