# Generated by Django 5.2.8 on 2025-12-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contest_game_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='age_group',
            field=models.CharField(blank=True, help_text='예: 20대, 30대, 40대 등', max_length=100, verbose_name='연령'),
        ),
        migrations.AddField(
            model_name='contest',
            name='event_type',
            field=models.CharField(blank=True, help_text='예: 단식, 복식, 혼합복식 등', max_length=100, verbose_name='종목'),
        ),
        migrations.AddField(
            model_name='contest',
            name='grade',
            field=models.CharField(blank=True, help_text='예: 1급, 2급, 3급 등', max_length=100, verbose_name='급수'),
        ),
    ]
