# Generated by Django 5.2.8 on 2025-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_contest_age_group_contest_event_type_contest_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='schedule_details',
            field=models.JSONField(blank=True, help_text='날짜별 경기 일정을 JSON 형식으로 입력하세요. 예: [{"date": "2025-12-20", "events": ["혼복"], "age": "전연령"}]', null=True, verbose_name='날짜별 경기 일정'),
        ),
    ]
