# Generated by Django 5.2.8 on 2025-12-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_contest_schedule_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_name',
            field=models.CharField(blank=True, help_text='접수처 이름을 입력하세요. 예: 배드민톡, 네이버 등', max_length=200, verbose_name='접수처 이름'),
        ),
    ]
