# Generated by Django 5.2.8 on 2025-12-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_contest_registration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='경기일')),
                ('events', models.JSONField(blank=True, help_text='혼복/여복/남복 복수 선택', null=True, verbose_name='경기 종목')),
                ('ages', models.JSONField(blank=True, help_text='10대~70대 또는 전연령 복수 선택', null=True, verbose_name='연령대')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contests.contest', verbose_name='대회')),
            ],
            options={
                'verbose_name': '경기 일정',
                'verbose_name_plural': '경기 일정',
                'ordering': ['date', 'id'],
            },
        ),
    ]
