# Generated by Django 5.2.8 on 2025-12-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_contestschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='game_events',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='schedule_details',
        ),
    ]
