# Generated by Django 5.2.8 on 2025-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_remove_contest_age_group_remove_contest_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='award_reward_text',
            field=models.TextField(blank=True, help_text='입상상품에 대한 상세 정보를 입력하세요.', verbose_name='입상상품'),
        ),
        migrations.AddField(
            model_name='contest',
            name='grade_division',
            field=models.TextField(blank=True, help_text='급수, 종목, 연령, 급수 정보를 입력하세요.', verbose_name='급수 (종목 / 연령 / 급수)'),
        ),
        migrations.AddField(
            model_name='contest',
            name='participant_target',
            field=models.TextField(blank=True, help_text='참가 대상에 대한 상세 정보를 입력하세요.', verbose_name='참가 대상'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, verbose_name='대회 요강 AI 요약'),
        ),
    ]
