# Generated by Django 5.2.8 on 2025-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_contest_award_reward_text_contest_grade_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='grade_division',
        ),
        migrations.AlterField(
            model_name='contest',
            name='participant_target',
            field=models.TextField(blank=True, help_text='참가 대상, 종목, 연령, 급수 정보를 입력하세요.', verbose_name='참가 대상 (종목 / 연령 / 급수)'),
        ),
    ]
