# Generated by Django 5.2.8 on 2025-12-21 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_remove_contest_grade_division_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_contests', to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
    ]
