# Generated by Django 5.2.8 on 2025-12-21 08:42

import django.db.models.deletion
from django.db import migrations, models


def migrate_sponsor_data(apps, schema_editor):
    """기존 sponsor 문자열 값을 Sponsor 객체로 변환"""
    Contest = apps.get_model('contests', 'Contest')
    Sponsor = apps.get_model('contests', 'Sponsor')
    
    # 기존 sponsor 문자열 값들을 수집 (sponsor_old 필드에서)
    sponsor_names = set()
    for contest in Contest.objects.all():
        # sponsor_old는 CharField이므로 직접 접근
        sponsor_value = getattr(contest, 'sponsor_old', None)
        if sponsor_value and sponsor_value.strip():
            sponsor_names.add(sponsor_value.strip())
    
    # Sponsor 객체 생성
    sponsor_map = {}
    for name in sponsor_names:
        if name:  # 빈 문자열 체크
            sponsor, created = Sponsor.objects.get_or_create(name=name)
            sponsor_map[name] = sponsor
    
    # Contest의 sponsor_new 필드를 Sponsor 객체로 업데이트
    for contest in Contest.objects.all():
        sponsor_value = getattr(contest, 'sponsor_old', None)
        if sponsor_value and sponsor_value.strip() and sponsor_value.strip() in sponsor_map:
            contest.sponsor_new = sponsor_map[sponsor_value.strip()]
            contest.save(update_fields=['sponsor_new'])


def reverse_migrate_sponsor_data(apps, schema_editor):
    """역방향 마이그레이션: Sponsor 객체를 문자열로 변환"""
    Contest = apps.get_model('contests', 'Contest')
    
    for contest in Contest.objects.all():
        if hasattr(contest, 'sponsor_new') and contest.sponsor_new:
            contest.sponsor_old = contest.sponsor_new.name
            contest.save(update_fields=['sponsor_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_contest_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='스폰서명')),
            ],
            options={
                'verbose_name': '스폰서',
                'verbose_name_plural': '스폰서',
                'ordering': ['name'],
            },
        ),
        # 기존 sponsor 필드를 sponsor_old로 이름 변경
        migrations.RenameField(
            model_name='contest',
            old_name='sponsor',
            new_name='sponsor_old',
        ),
        # 새 ForeignKey 필드 추가
        migrations.AddField(
            model_name='contest',
            name='sponsor_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests_new', to='contests.sponsor', verbose_name='스폰서'),
        ),
        # 데이터 마이그레이션
        migrations.RunPython(migrate_sponsor_data, reverse_migrate_sponsor_data),
        # 기존 sponsor_old 필드 제거
        migrations.RemoveField(
            model_name='contest',
            name='sponsor_old',
        ),
        # 새 필드 이름을 sponsor로 변경
        migrations.RenameField(
            model_name='contest',
            old_name='sponsor_new',
            new_name='sponsor',
        ),
    ]
