# Generated by Django 5.2.8 on 2025-12-21 08:43

from django.db import migrations


def add_initial_sponsors(apps, schema_editor):
    Sponsor = apps.get_model('contests', 'Sponsor')
    sponsors = [
        '요넥스',
        '빅터',
        '리닝',
        '미즈노',
        '아펙스',
        '체고',
        '테크니스트',
        '트라이온',
        '스트로커스',
        '트리코어',
        'kbb',
    ]
    for sponsor_name in sponsors:
        Sponsor.objects.get_or_create(name=sponsor_name)


def remove_initial_sponsors(apps, schema_editor):
    Sponsor = apps.get_model('contests', 'Sponsor')
    sponsors = [
        '요넥스',
        '빅터',
        '리닝',
        '미즈노',
        '아펙스',
        '체고',
        '테크니스트',
        '트라이온',
        '스트로커스',
        '트리코어',
        'kbb',
    ]
    Sponsor.objects.filter(name__in=sponsors).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_sponsor_alter_contest_sponsor'),
    ]

    operations = [
        migrations.RunPython(add_initial_sponsors, remove_initial_sponsors),
    ]
