# Generated by Django 5.2.8 on 2025-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_add_initial_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='map_url',
            field=models.URLField(blank=True, help_text='지도 링크를 추가할 수 있습니다.', verbose_name='지도 URL'),
        ),
        migrations.AddField(
            model_name='contest',
            name='region',
            field=models.CharField(blank=True, choices=[('', '지역 선택'), ('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('부산', '부산'), ('대구', '대구'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('강원', '강원'), ('세종', '세종'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주')], help_text='대회가 열리는 지역을 선택하세요.', max_length=20, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='location',
            field=models.CharField(help_text='정확한 위치를 입력하세요.', max_length=200, verbose_name='상세 위치'),
        ),
    ]
