# Generated by Django 5.2.8 on 2025-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_contest_map_url_contest_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='location',
            field=models.CharField(blank=True, help_text='정확한 위치를 입력하세요.', max_length=200, verbose_name='상세 위치'),
        ),
    ]
