# Generated by Django 5.2.8 on 2025-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_alter_contest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='region',
        ),
        migrations.AlterField(
            model_name='contest',
            name='location',
            field=models.CharField(max_length=200, verbose_name='장소'),
        ),
    ]
