# Generated by Django 5.2.8 on 2025-12-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_remove_contest_map_url_remove_contest_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(help_text='URL에서 사용할 고유 값입니다.', max_length=75, unique=True, verbose_name='슬러그'),
        ),
    ]
