# Generated by Django 5.2.8 on 2025-12-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_alter_contest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(help_text='URL에서 사용할 고유 값입니다.', max_length=45, unique=True, verbose_name='슬러그'),
        ),
    ]
