# Generated by Django 5.2.8 on 2025-12-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0021_alter_contest_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contest_images/', verbose_name='이미지')),
                ('order', models.PositiveIntegerField(default=0, help_text='이미지 표시 순서를 지정합니다.', verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contests.contest', verbose_name='대회')),
            ],
            options={
                'verbose_name': '대회 이미지',
                'verbose_name_plural': '대회 이미지',
                'ordering': ['order', 'id'],
            },
        ),
    ]
