# Generated by Django 5.2.8 on 2025-12-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0022_contestimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestimage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contestimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='이미지 표시 순서 (작은 숫자가 먼저 표시됨)', verbose_name='순서'),
        ),
    ]
