# Generated by Django 5.2.8 on 2025-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0023_remove_contestimage_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='location',
        ),
        migrations.AddField(
            model_name='contest',
            name='region',
            field=models.CharField(choices=[('all', '전체'), ('capital', '수도권'), ('busan', '영남권'), ('daegu', '대구권'), ('gwangju', '호남권'), ('daejeon', '충청권'), ('ulsan', '울산권'), ('jeju', '제주권')], default='all', max_length=20, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='contest',
            name='region_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='상세 장소'),
        ),
    ]
