# Generated by Django 5.2.8 on 2025-12-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0024_remove_contest_location_contest_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('부산', '부산'), ('대구', '대구'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('강원', '강원'), ('세종', '세종'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주')], default='서울', max_length=20, verbose_name='지역'),
        ),
    ]
