# Generated by Django 5.2.8 on 2025-12-26 09:35

import contests.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0025_alter_contest_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=contests.models.contest_image_upload_to, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='contests.sponsor', verbose_name='스폰서'),
        ),
        migrations.AlterField(
            model_name='contestimage',
            name='image',
            field=models.ImageField(upload_to=contests.models.contest_image_upload_to, verbose_name='이미지'),
        ),
    ]
