# Generated by Django 5.2.8 on 2025-12-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_alter_contest_image_alter_contest_sponsor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='image',
        ),
    ]
