# Generated by Django 5.2.8 on 2025-12-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0027_remove_contest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL에서 사용할 고유 값입니다.', max_length=45, unique=True, verbose_name='슬러그'),
        ),
    ]
