# Generated by Django 5.2.8 on 2026-01-06 00:33

import contests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0028_alter_contest_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['schedule_start', '-created_at'], 'verbose_name': '전국 배드민턴 대회', 'verbose_name_plural': '전국 배드민턴 대회'},
        ),
        migrations.AddField(
            model_name='contest',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='대회 요강 원본 PDF 파일을 업로드하세요.', null=True, upload_to=contests.models.contest_pdf_upload_to, verbose_name='대회 요강 PDF'),
        ),
    ]
