# Generated by Django 5.2.8 on 2026-02-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0030_contest_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='award_reward',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='event_division',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participant_reward',
        ),
        migrations.AlterField(
            model_name='contest',
            name='registration_end',
            field=models.DateField(blank=True, null=True, verbose_name='접수 종료일'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='registration_start',
            field=models.DateField(blank=True, null=True, verbose_name='접수 시작일'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL에서 사용할 고유 값입니다.', max_length=37, unique=True, verbose_name='슬러그'),
        ),
    ]
