# Generated by Django 5.2.8 on 2026-02-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0031_registration_dates_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participant_ages',
            field=models.CharField(blank=True, help_text='예: 20대 ~ 60대, 전연령', max_length=200, verbose_name='연령'),
        ),
        migrations.AddField(
            model_name='contest',
            name='participant_events',
            field=models.CharField(blank=True, help_text='예: 남복, 여복, 혼복, 단식', max_length=200, verbose_name='종목'),
        ),
        migrations.AddField(
            model_name='contest',
            name='participant_grades',
            field=models.CharField(blank=True, help_text='예: A, B, C, D, 초심, 입문', max_length=200, verbose_name='급수'),
        ),
    ]
