# Generated by Django 5.2.8 on 2026-02-05 13:07

import badmintok.fields
import contests.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0032_add_participant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestimage',
            name='image',
            field=badmintok.fields.WebPImageField(upload_to=contests.models.contest_image_upload_to, verbose_name='이미지'),
        ),
    ]
