# Generated by Django 5.2.8 on 2026-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0033_alter_contestimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='shuttlecock',
            field=models.CharField(blank=True, help_text='예: 닉텐 T-Black, 요넥스 AS-50 등', max_length=100, verbose_name='사용구'),
        ),
    ]
