# Generated by Django 5.2.8 on 2026-03-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0034_contest_shuttlecock'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestschedule',
            name='description',
            field=models.CharField(blank=True, help_text='직접 입력 시 체크박스 대신 이 내용이 표시됩니다. 예: 혼복 전 경기, 60대 이상 남·여복 전 경기', max_length=500, verbose_name='일정 설명'),
        ),
    ]
