# Generated by Django 5.2.8 on 2026-03-29 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0035_add_schedule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participation_prize',
            field=models.CharField(blank=True, help_text='예: 셔틀콕 1통, 수건 등', max_length=200, verbose_name='참가상'),
        ),
        migrations.AddField(
            model_name='contest',
            name='raffle_prize',
            field=models.CharField(blank=True, help_text='예: 라켓 추첨, 가방 추첨 등', max_length=200, verbose_name='경품'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='award_reward_text',
            field=models.TextField(blank=True, help_text='기존 입상상품 텍스트. 조별 입상상품이 등록되면 조별 데이터가 우선 표시됩니다.', verbose_name='입상상품 (텍스트)'),
        ),
        migrations.CreateModel(
            name='ContestPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(help_text='예: 동호인조, 자강조, A조, 초심조 등', max_length=100, verbose_name='조 구분')),
                ('first_prize', models.CharField(blank=True, max_length=200, verbose_name='1위 상품')),
                ('second_prize', models.CharField(blank=True, max_length=200, verbose_name='2위 상품')),
                ('third_prize', models.CharField(blank=True, max_length=200, verbose_name='3위 상품')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='contests.contest', verbose_name='대회')),
            ],
            options={
                'verbose_name': '입상상품 (조별)',
                'verbose_name_plural': '입상상품 (조별)',
                'ordering': ['id'],
            },
        ),
    ]
