# Generated by Django 5.2.8 on 2026-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0036_add_contest_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestprize',
            name='division',
            field=models.CharField(max_length=100, verbose_name='조 구분'),
        ),
    ]
