# Generated by Django 5.2.8 on 2026-03-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0037_alter_prize_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestprize',
            name='division',
            field=models.CharField(help_text='동호인조, 준자강조, 자강조 등', max_length=100, verbose_name='조 구분'),
        ),
    ]
