# Generated by Django 5.2.8 on 2026-04-16 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0038_update_prize_division_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_test',
            field=models.BooleanField(default=False, help_text='자동 업로더 테스트용 데이터. 관리자 목록에서 일괄 필터·삭제에 사용합니다.', verbose_name='테스트 데이터'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('부산', '부산'), ('대구', '대구'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('강원', '강원'), ('세종', '세종'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주'), ('기타', '기타')], default='서울', max_length=20, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='URL에서 사용할 고유 값입니다.', max_length=100, unique=True, verbose_name='슬러그'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['title', 'schedule_start'], name='contest_title_start_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['is_test'], name='contest_is_test_idx'),
        ),
    ]
